export const refs = {
  inputBox: document.getElementById("input-box"),
  tagsInput: document.getElementById("tags-input"),
  currentTagsContainer: document.getElementById("current-tags"),
  addTagButton: document.getElementById("add-tag-button"),
  listContainer: document.getElementById("list-container"),
  completedCounter: document.getElementById("completed-counter"),
  uncompletedCounter: document.getElementById("uncompleted-counter"),
  searchBar: document.getElementById("search-input"),
  sortDropdown: document.getElementById("sort-dropdown"),
  modal: document.getElementById("myModal"),
  closeButton: document.querySelector(".close-button"),
  okButton: document.getElementById("modalOkButton"),
  cancelButton: document.getElementById("modalCancelButton"),
  modalMessage: document.getElementById("modalMessage"),
  modalInput: document.getElementById("modalInput"),
};
